extraction:
  cpp:
    after_prepare: 
      - python report.py 31
  cobol:
    after_prepare: 
      - python report.py 31
  csharp:
    after_prepare: 
      - python report.py 31
  java:
    after_prepare: 
      - python report.py 31
  javascript:
    after_prepare: 
      - python report.py 31
  python:
    after_prepare: 
      - python report.py 31
